AWSTemplateFormatVersion: '2010-09-09'
Description: HTTP API Gateway -> Lambda (POST/GET /register) with CORS + Access Logs.

Parameters:
  ProjectName:
    Type: String
    Default: visitor-app

  Environment:
    Type: String
    Default: dev

  VisitorLambdaArn:
    Type: String
    Description: Lambda ARN passed from the Lambda nested stack

Resources:
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/vendedlogs/apis/${ProjectName}-${Environment}-access-logs"
      RetentionInDays: 7

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-api"
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['GET','POST','OPTIONS']
        AllowHeaders: ['Content-Type']

  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: '2.0'
      IntegrationUri: !Sub
        - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FnArn}/invocations"
        - FnArn: !Ref VisitorLambdaArn

  PostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /register"
      Target: !Sub "integrations/${LambdaIntegration}"

  GetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /register"
      Target: !Sub "integrations/${LambdaIntegration}"

  DefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true
      AccessLogSettings:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","httpMethod":"$context.httpMethod","routeKey":"$context.routeKey","status":"$context.status","responseLength":"$context.responseLength"}'

  InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VisitorLambdaArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*"

Outputs:
  StackName:
    Value: !Ref AWS::StackName

  ApiId:
    Value: !Ref HttpApi

  ApiBaseUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  RegisterEndpoint:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/register"

  AccessLogGroupName:
    Value: !Ref ApiAccessLogGroup